# directory
from __future__ import annotations
import yaml

# with open('/home/ubuntu/ai_trading/config/config.yaml', 'r') as config:
with open('/home/bhumika/Desktop/AlgoTrader/ai_trading/config/config.yaml', 'r') as config:
    file = yaml.safe_load(config)

STATUS = file['status']
CONFIG = file['dev'] if STATUS == 'DEV' else file['prod']

DATA_SAVE_DIR = "datasets"
TRAINED_MODEL_DIR = "trained_model"
TENSORBOARD_LOG_DIR = "tensorboard_log"
RESULTS_DIR = "result"

# date format: '%Y-%m-%d'
# bug fix: set Monday right, start date set 2014-01-01 ValueError:
# all the input array dimensions for the concatenation axis must match exactly, but along dimension 0,
# the array at index 0 has size 1658 and the array at index 1 has size 1657
TRAIN_START_DATE = "2014-01-01"
TRAIN_END_DATE = "2020-12-30"

TEST_START_DATE = "2021-01-01"
TEST_END_DATE = "2022-12-30"

TRADE_START_DATE = "2021-01-01"
TRADE_END_DATE = "2022-12-30"

# stockstats technical indicator column names
# check https://pypi.org/project/stockstats/ for different names

tech_list = ['aroond_14', 'aroonosc_14', 'aroonu_14', 'bbb_5_2_0', 'bbl_5_2_0', 'bbm_5_2_0', 'bbp_5_2_0', 'bbu_5_2_0',
             'cdl_doji_10_0_1', 'cdl_inside', 'close', 'cti_14', 'ema_10', 'ema_20', 'ema_50', 'eps',
             'high', 'humidity', 'low', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9',
             'maxtempc', 'mfi_14', 'mintempc', 'mom_1', 'natr_20', 'netprofit',
             'news_sentiment', 'open', 'opm', 'pbt', 'pe', 'precipmm', 'pressure',
             'roe', 'rsi_14', 'sma_10', 'sma_20', 'sma_50', 'stochd_14_3_3',
             'stochk_14_3_3', 'supert_10_2_0', 'supertd_10_2_0', 'supertl_10_2_0', 'superts_10_2_0', 'tweets_sentiment', 'visibility',
             'volume', 'vwma_10', 'vwma_20', 'vwma_50', 'windspeedkmph', 'wma_10', 'wma_20', 'wma_50']

location_list_US = ['chicago', 'phoenix', 'philadelphia', 'dallas']
location_list_IND = ['Mumbai', 'Delhi', 'Kolkata', 'Lucknow', 'Chennai']

US_25 = ['AAPL', 'MSFT', 'AMZN', 'NVDA', 'GOOGL', 'NKE', 'GOOG',
         'TSLA', 'UNH', 'META', 'XOM', 'JNJ', 'JPM', 'V', 'PG', 'HD', 'MA', 'ABBV',
         'CVX', 'AVGO', 'MRK', 'LLY', 'PEP', 'KO', 'PFE']

NIFTY_10 = ['ADANIPORTS.NS', 'APOLLOHOSP.NS', 'ASIANPAINT.NS', 'AXISBANK.NS',
            'BAJAJ-AUTO.NS', 'BAJFINANCE.NS',
            'BAJAJFINSV.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BRITANNIA.NS']

NIFTY_50 = ['ADANIPORTS', 'APOLLOHOSP', 'ASIANPAINT', 'AXISBANK', 'BAJAJ-AUTO',
            'BAJFINANCE', 'BAJAJFINSV', 'BPCL', 'BHARTIARTL', 'BRITANNIA',
            'CIPLA', 'HDFCBANK', 'COALINDIA', 'DIVISLAB', 'DRREDDY',
            'EICHERMOT', 'GRASIM', 'HCLTECH', 'HDFCLIFE', 'HEROMOTOCO',
            'HINDALCO', 'HINDUNILVR', 'HDFC', 'ICICIBANK', 'ITC', 'INDUSINDBK',
            'INFY', 'JSWSTEEL', 'KOTAKBANK', 'LT', 'M&M', 'MARUTI', 'NTPC',
            'NESTLEIND', 'ONGC', 'POWERGRID', 'RELIANCE', 'SBILIFE',
            'SHREECEM', 'SBIN', 'SUNPHARMA', 'TCS', 'TATACONSUM', 'TATAMOTORS',
            'TATASTEEL', 'TECHM', 'TITAN', 'UPL', 'ULTRACEMCO', 'WIPRO']

US_symbols = ['SCOR',
              'KLXE',
              'NVEC',
              'BSBK',
              'FNLC',
              'AXON',
              'AGNC',
              'OPTN',
              'STRS',
              'NMRK',
              'SLAC',
              'SEV',
              'CVCY',
              'NVCR',
              'STRT',
              'CEAD',
              'STSA',
              'FNKO',
              'SLAB',
              'STRR',
              'CVCO',
              'NVCT',
              'NVEI',
              'CMRA',
              'CMRX',
              'SDC',
              'NMRD',
              'IFRX',
              'AGLE',
              'TWST',
              'EGTS.CA.CA',
              'JUFO.CA.CA',
              'ETEL.CA.CA',
              'GGAL.BA',
              'COME.BA',
              'TECO2.BA',
              'YPFD.BA',
              'ALUA.BA',
              'PAMP.BA',
              'BMA.BA',
              'EDN.BA',
              'CENCOSUD.SN',
              'ENELCHILE.SN',
              'CONCHATORO.SN',
              'IAM.SN',
              'SONDA.SN',
              'RIPLEY.SN',
              'ANDINA-B.SN',
              'CHILE.SN',
              'SECURITY.SN',
              'ENTEL.SN',
              'BCI.SN',
              'MALLPLAZA.SN',
              'ENELAM.SN',
              'VAPORES.SN',
              'AGUAS-A.SN',
              'FALABELLA.SN',
              'BSANTANDER.SN',
              'LTM.SN',
              'PARAUCO.SN',
              'SALFACORP.SN',
              'SQM-B.SN',
              'COPEC.SN',
              'CMPC.SN',
              'ILC.SN',
              'CAP.SN',
              'CCU.SN',
              'ECL.SN',
              'COLBUN.SN',
              'CUERVO.MX',
              'FEMSAUBD.MX',
              'OMAB.MX',
              'GAPB.MX',
              'GRUMAB.MX',
              'MEGACPO.MX',
              'PINFRA.MX',
              'BIMBOA.MX',
              'ASURB.MX',
              'ALSEA.MX',
              'GMEXICOB.MX',
              'BBAJIOO.MX',
              'GFNORTEO.MX',
              'BOLSAA.MX',
              'GCARSOA1.MX',
              'GCC.MX',
              'ALPEKA.MX',
              'TLEVISACPO.MX',
              'LABB.MX',
              'GENTERA.MX',
              'KIMBERA.MX',
              'AC.MX',
              'CEMEXCPO.MX',
              'RADL3.SA',
              'BBDC4.SA',
              'SBSP3.SA',
              'ITSA4.SA',
              'USIM5.SA',
              'MULT3.SA',
              'BRKM5.SA',
              'KLBN11.SA',
              'PETR4.SA',
              'EQTL3.SA',
              'BBDC3.SA',
              'CMIG4.SA',
              'UGPA3.SA',
              'ENBR3.SA',
              'PETR3.SA',
              'ECOR3.SA',
              'CCRO3.SA',
              'JBSS3.SA',
              'OIBR4.SA',
              'LREN3.SA',
              'BBSE3.SA',
              '6947.KL',
              '1155.KL',
              '1295.KL',
              '7277.KL',
              '4065.KL',
              '5183.KL',
              '7084.KL',
              '5681.KL',
              '2445.KL',
              '1066.KL',
              '1961.KL',
              '4707.KL',
              '6888.KL',
              '4715.KL',
              '4197.KL',
              '6012.KL',
              '1023.KL',
              '5296.KL',
              '5347.KL',
              '5225.KL',
              '8869.KL',
              '5819.KL',
              '1015.KL',
              '6033.KL',
              '4863.KL',
              '3816.KL',
              '5285.KL',
              '1082.KL',
              '3182.KL',
              '0166.KL',
              'PNBN.JK',
              'FMII.JK',
              'LPGI.JK',
              'FPNI.JK',
              'BKDP.JK',
              'SPMA.JK',
              'EXCL.JK',
              'SHID.JK',
              'KDSI.JK',
              'ASGR.JK',
              'INDR.JK',
              'AISA.JK',
              'UNIC.JK',
              'VOKS.JK',
              'ASDM.JK',
              'BABP.JK',
              'SQMI.JK',
              'CITA.JK',
              'PSKT.JK',
              'LMPI.JK',
              'JSMR.JK',
              'AIMS.JK',
              'ARGO.JK',
              'PRAS.JK',
              'SULI.JK',
              'PUDP.JK',
              'EMI.SI',
              'C52.SI',
              'S58.SI',
              'G13.SI',
              'J36.SI',
              'D05.SI',
              'C07.SI',
              'H78.SI',
              'S63.SI',
              'O39.SI',
              'A17U.SI',
              'Z74.SI',
              'V03.SI',
              'C09.SI',
              'ME8U.SI',
              'AJBU.SI',
              'C38U.SI',
              'BN4.SI',
              'N2IU.SI',
              'M44U.SI',
              'U14.SI',
              'U11.SI',
              'U96.SI',
              'F34.SI',
              'BUOU.SI',
              '9CI.SI',
              'D01.SI',
              'YF8.SI',
              'Y92.SI',
              'BS6.SI',
              'JRI',
              'SDR',
              'SCS',
              'BCC',
              'BBY',
              'SCU',
              'CMSD',
              'BBW',
              'JSD',
              'SLAC',
              'JRS',
              'CMSC',
              'BBN',
              'BBU',
              'BCE',
              'SCX',
              'JRO',
              'CMRE',
              'UCB.BR',
              'KBC.BR',
              'COFB.BR',
              'ONTEX.BR',
              'INGA.BR',
              'EDEN.PA',
              'RAND.AS',
              'TEP.PA',
              'BN.PA',
              'GALP.LS',
              'HO.PA',
              'AIR.PA',
              'CAP.PA',
              'SHELL.AS',
              'JMT.LS',
              'ASML.AS',
              'VIE.PA',
              'LR.PA',
              'ASM.AS',
              'MC.PA',
              'OR.PA',
              'SAN.PA',
              'AGS.BR',
              'GBLB.BR',
              'ERF.PA',
              'SW.PA',
              'ABI.BR',
              'STLAP.PA',
              'KBC.BR',
              'AMUN.PA',
              'KER.PA',
              'AGN.AS',
              'BNP.PA',
              'INGA.AS',
              'PHIA.AS',
              'BN.PA',
              'DTE.DE',
              'AI.PA',
              'ITX.MC',
              'ALV.DE',
              'ENI.MI',
              'ORA.PA',
              'AIR.PA',
              'ENGI.PA',
              'BAYN.DE',
              'ENEL.MI',
              'SAF.PA',
              'DPW.DE',
              'IBE.MC',
              'ASML.AS',
              'MC.PA',
              'OR.PA',
              'G.MI',
              'CA.PA',
              'SU.PA',
              'SAN.PA',
              'BMW.DE',
              'ABI.BR',
              'BBVA.MC',
              'BNP.PA',
              'INGA.AS',
              'FRE.DE',
              'PHIA.AS',
              'DBK.DE',
              '0003.HK',
              '0101.HK',
              '9633.HK',
              '6098.HK',
              '0002.HK',
              '1398.HK',
              '1044.HK',
              '1810.HK',
              '0992.HK',
              '0012.HK',
              '9988.HK',
              '1209.HK',
              '1038.HK',
              '0669.HK',
              '0017.HK',
              '1093.HK',
              '2628.HK',
              '0883.HK',
              '0027.HK',
              '0267.HK',
              '3690.HK',
              '1109.HK',
              '2331.HK',
              '2319.HK',
              '9618.HK',
              '0241.HK',
              '6690.HK',
              '2269.HK',
              '2020.HK',
              '2688.HK',
              'ML.PA',
              'BN.PA',
              'CAP.PA',
              'AI.PA',
              'HO.PA',
              'ORA.PA',
              'ENGI.PA',
              'DG.PA',
              'AIR.PA',
              'RI.PA',
              'ATO.PA',
              'VIE.PA',
              'SU.PA',
              'AC.PA',
              'LR.PA',
              'MC.PA',
              'CA.PA',
              'OR.PA',
              'SGO.PA',
              'SAN.PA',
              'VIV.PA',
              'SW.PA',
              'EN.PA',
              'KER.PA',
              'WLN.PA',
              'ACA.PA',
              'BNP.PA',
              'GLE.PA',
              'RWE.DE',
              'P911.DE',
              'DTE.DE',
              'ALV.DE',
              'DTG.DE',
              'AIR.DE',
              'ZAL.DE',
              'BAYN.DE',
              'BEI.DE',
              'EOAN.DE',
              'SY1.DE',
              'MRK.DE',
              'DPW.DE',
              'SIE.DE',
              'BMW.DE',
              'ADS.DE',
              'IFX.DE',
              'MTX.DE',
              'VOW3.DE',
              'HNR1.DE',
              'SHL.DE',
              'DB1.DE',
              'ENR.DE',
              '1COV.DE',
              'BAS.DE',
              'HEI.DE',
              'CON.DE',
              'FRE.DE',
              'VNA.DE',
              'DBK.DE',
              'SCOR',
              'KLXE',
              'NVEC',
              'BSBK',
              'FNLC',
              'AXON',
              'AGNC',
              'OPTN',
              'STRS',
              'NMRK',
              'SLAC',
              'SEV',
              'CVCY',
              'NVCR',
              'STRT',
              'CEAD',
              'STSA',
              'FNKO',
              'SLAB',
              'STRR',
              'CVCO',
              'NVCT',
              'NVEI',
              'CMRA',
              'CMRX',
              'SDC',
              'NMRD',
              'IFRX',
              'AGLE']

# Model Parameters
A2C_PARAMS = {"n_steps": 5, "ent_coef": 0.01, "learning_rate": 0.0007}
PPO_PARAMS = {
    "n_steps": 2048,
    "ent_coef": 0.01,
    "learning_rate": 0.00025,
    "batch_size": 64,
}
DDPG_PARAMS = {"batch_size": 128, "buffer_size": 50000, "learning_rate": 0.001}
TD3_PARAMS = {"batch_size": 100,
              "buffer_size": 1000000, "learning_rate": 0.001}
SAC_PARAMS = {
    "batch_size": 64,
    "buffer_size": 100000,
    "learning_rate": 0.0001,
    "learning_starts": 100,
    "ent_coef": "auto_0.1",
}
ERL_PARAMS = {
    "learning_rate": 3e-5,
    "batch_size": 2048,
    "gamma": 0.985,
    "seed": 312,
    "net_dimension": 512,
    "target_step": 5000,
    "eval_gap": 30,
    # bug fix:KeyError: 'eval_times' line 68, in get_model model.eval_times = model_kwargs["eval_times"]
    "eval_times": 64,
}
RLlib_PARAMS = {"lr": 5e-5, "train_batch_size": 500, "gamma": 0.99}


# Possible time zones
TIME_ZONE_SHANGHAI = "Asia/Shanghai"  # Hang Seng HSI, SSE, CSI
TIME_ZONE_USEASTERN = "US/Eastern"  # Dow, Nasdaq, SP
TIME_ZONE_PARIS = "Europe/Paris"  # CAC,
TIME_ZONE_BERLIN = "Europe/Berlin"  # DAX, TECDAX, MDAX, SDAX
TIME_ZONE_JAKARTA = "Asia/Jakarta"  # LQ45
# If neither of the above is your time zone, you should define it, and set USE_TIME_ZONE_SELFDEFINED 1.
TIME_ZONE_SELFDEFINED = "xxx"
USE_TIME_ZONE_SELFDEFINED = 0  # 0 (default) or 1 (use the self defined)
